name: aml_env

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3
  - numpy
  - scipy
  - yaml
  - "pandas==1.0.5"
  - "scikit-learn>=0.21"
  - matplotlib
  - "lightgbm==3.0.0"
  - "plotly==4.12.0"
  - "coloredlogs==14.0"
  - "joblib==0.16.0"
  - "keras==2.4.3"
  - "PyYAML==5.3.1"
  - "xgboost==1.2.1"
  - "autofeat==1.1.3"
  - "imbalanced_learn==0.7.0"
