# Pipeline steps
persistence:
  load_from_file: true
  save_to_file: true

preproc:

  oversampling:
    method: ADASYN

  imputer:
    strategy: median # mean, median

  zero_and_const:
    enabled: false
    cvmin: 0.0001

  outlier: # random forest
    enabled: true
    cont_lim: 0.05
    impl: ines
  
  rmf:
    pipeline: rfe # auto, rfe, ffu

    rfe:
      method: rfe # rfecv
      estimator: svc_rfe # SVC_RFE
      min_feat: 900 # default 20
      step_size: 50 # default 10

    pca:
      enabled: false 
      n_comp: 2

  normalize:
    enabled: true
    method: standard
    use_pretrained_for_X_u: True
    
fit_model: svc

# TODO: add class_weight
models:
  svc_rfe:
    C: 1.0 
    kernel: 'linear' # rbf kernel does not work for RFE
  svc:
    C: 1.0 
    kernel: 'rbf' 
    degree: 3 # ignored if kernel not poly
    gamma: 'scale' 
    coef0: 0.0 # Independent term in kernel function. It is only significant in ‘poly’ and ‘sigmoid’.
    shrinking: True # What it this?
    probability: False 
    tol: 0.001 
    verbose: True 
    max_iter: -1 # no limit
    decision_function_shape: 'ovo' #ovo or ovr
    break_ties: False 

  lightgbm:
    num_leaves: 127 # default 31
    learning_rate: 0.1 # default 0.1
    num_iterations: 1000 # default 100
    boosting_type: dart # default gbdt [dart, goss, rf]
    # TODO: add these params
    # boosting_type=run_cfg['models/lightgbm/boosting_type'],
    # class_weight=run_cfg['models/lightgbm/class_weight'],
    # num_leaves=run_cfg['models/lightgbm/num_leaves'],
    # learning_rate=run_cfg['models/lightgbm/learning_rate'],
    # n_estimators=run_cfg['models/lightgbm/num_iterations'

cv_tasks:
  # - lightgbm
  - svc
  # - lasso
  # - ridge
  # - elasticnet

overfit:
  test_size: 0.3